FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# Use `npm install` (installs dev deps required for building) when package-lock.json is not present
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
